### ISSUE TITLE
Star system creation

### ISSUE THREAD

**Issue by rc14193** [yoel123/java-text-based-space-station-manger-sim#15]
&nbsp;Since there's going to be warping, there need to be different star systems right? This means having random generation for both the number of stars and the number of planets around a star. 

&nbsp;For this it would make sense to also generate attributes for both the stars and the planets around this. I would propose the creation of a star class that first generates its own attributes, e.g. type of star, size of star, any hazards it has. This class would then call the planet class to generate the planets around it. The planets would have their own attributes, size, gas or rock, hazards, other faction present.

&nbsp;How to organize navigation would likely be its own issue to address in another topic.

**Comment by yoel123** [comment]
no there's no need for this game, its not a 4x, its more of a base-building game with economics and combat and events to spice things up.

this might be extreme luxury features.

the player will send fleets on missions but the locations won't have many features or attribute to make a class for them, maybe a modal class that holds data. think of these as multi: step/turn events nothing more.

I want to make this game as simple as possible to play and program, think of those other system stars, enemy stations (pirate base) as abstract concepts, not as an important feature.

you see when you add this you need to consider things like nav and map etc...I don't want to focus on these things as of now.
