### ISSUE TITLE
Invalid input for event causes crash

### ISSUE THREAD

**Issue by rc14193** [yoel123/java-text-based-space-station-manger-sim#16]
Found a bug where if you go to the events page and type an invalid input it cause an exception error that crashes the game. Need to have a check here that if the input is invalid to notify the user then reprint the screen.

![image](https://user-images.githubusercontent.com/62862738/94878196-b4991180-042a-11eb-85d2-4aed96fe664b.png)

**Comment by yoel123** [comment]
this happened because at the start events is empty, add an if that checks events size.

fixed the problem.
