### ISSUE TITLE
market: sell/buy  all

### ISSUE THREAD

**Issue by yoel123** [yoel123/java-text-based-space-station-manger-sim#42]
I want to add the ability to sell or buy all from a certain item, instead of typing the amount every time.

like: you have 1472  fuel and you want to sell it all when asked for an amount you will write "all" instead of typing a  number, while you will be able to sell an amount I want the ability to sell all in one command.

for that the input will have to get a string instead of an int, you will have to check if its a number or text.

gyinput has a static method called is_num that does just that if its a number it will return true.

the rest I leave to you this shouldn't be too hard to code.

maybe as a challenge add a "sell half" command

**Comment by s-i-d-i** [comment]
Hello, I would like to work on this. Could you assign it to me?

**Comment by yoel123** [comment]
ok contact me via the contact form.
