### ISSUE TITLE
cargo limit

### ISSUE THREAD

**Issue by yoel123** [yoel123/java-text-based-space-station-manger-sim#7]
every item takes space, and space in the station's cargo hold is limited, it might be more the most ships can carry, but still thers need to be a limit.

doing player.cargo_limit=50 is easy.

calculating the total items amount also shod be easy.

also, there can be an upgrade for that "huge cargo hold" for an even bigger cargo hold.

**Comment by rc14193** [comment]
With all the different attributes now for items do you think it would be good to convert the db items to nested hash maps? I think it would make development and readability easier as it’s easier to understand map.get(“fuel”).get(“amount”) than rdata[1]. I could work on making that conversion and add a size key. I would think for the upgrades have them as an item too then just have their size be a negative number.

**Comment by yoel123** [comment]
it's unrelated to cargo limit issue.

thers no need to call an item data by writing "rdata[1]" for that I made the item modal so you can call it like this: item.amount.
you can get an item by name from market using get_item("some name") method, it returns an item model object.

market items attribute is an ArrayList you can get its size by calling size().

**Comment by yoel123** [comment]
done, was very easy to implement, shod have left this for other contributors.
